[package]
name = "desktop_logo_cli"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = { workspace = true }
desktop_logo_core = { path = "../core" }
